### PR TITLE
blog amdgpu

### PR DESCRIPTION
**Pull request by jcfrosty**
New AMDGPU blog.

### CODE REVIEW

**Comment by Enlik** [comment]
(continuing from issue #54)
Title suggests 26.06, file name 24.06. Minor stuff but can be annoying when someone gets misguided by this whilst doing something with the repository.

**Comment by jcfrosty** [comment]
Good point on the naming and the display code conversion. I've fixed the article to say DAL/HAL conversion. Also updated the name to remove confusion with releases.

**Review by Enlik — APPROVED** [review]

**Comment by Ryuno-Ki** [comment]
I still would like to have seen more subheadings, but you already tool over our suggestions and Enlik approved it, so...

Thanks for your contribution!

@Enlik will you take care for publication?

**Comment by Enlik** [comment]
I used it to mark "I think it's OK" for no better button or icon (I could have used a comment though).

I don't know how to publish the article; I thought you would do it. :)

**Comment by jcfrosty** [comment]
This would be a great learning opportunity. Since mudler invited me to the
group that can commit changes and stuff. Mind teaching us the process?

**Comment by Ryuno-Ki** [comment]
Ah, [it's already live](https://next.sabayon.org/article/AMDGPU_20170624/).

After digging through my IRC logs (thanks, @optiz0r!) I found out how we did it.
This may be worth documenting in our README.md.

When accepting a Pull Request, [Circle CI kicks in](https://circleci.com/gh/Sabayon/sabayon-website-next). It merges the changes into gh-pages, so they show up on [Sabayon's GitHub Page](http://sabayon.github.io/sabayon-website-next/blog/) and are synched to the live instance quickly afterwards.

**Comment by optiz0r** [comment]
Bullet points in "So when can we expect to see support" paragraph haven't rendered properly. Otherwise LGTM.

**Comment by jcfrosty** [comment]
I've gone ahead and fixed the bullet points. Seems it needed a line between the paragraph and the bullet lines.

**Comment by Enlik** [comment]
> Ah, it's already live.

It's actually only on the "next.sabayon.org" (I'm not sure if you meant that).

**Comment by Enlik** [comment]
Ugh, not sure how others thing but I'd prefer this PR (that consists of several small commits) be either merged or squashed.
Not a big issue anyway.

**Comment by jcfrosty** [comment]
So how does it go live to the main site?

**Comment by Ryuno-Ki** [comment]
@Enlik Lately I work mostly with rebases, but can pick another strategy next time.

@jcfrosty Circle CI takes care of that.

**Comment by Enlik** [comment]
FYI, it looks like it has to be merged manually to the production repository. @jcfrosty opened a PR there.

**Comment by Ryuno-Ki** [comment]
Ah, yes. How could I forget Sabayon/woohoo?!

**Pull request merged**
