### PR TITLE
Separate content from layout

### PR DESCRIPTION
**Pull request by Ryuno-Ki**
I'm in the process of cleaning up the markup in the content directory.

Please provide feedback if you're unhappy with certain design decisions. I'm keen on writing semantic markup.

Concerning index.html: IMHO The index.html should only contain the skeleton, so I will move the sections into "partials" in order to break them up later on (as with the markdown files in content).
Benefit: They hopefully become translatable.

### CODE REVIEW

**Comment by mudler** [comment]
sounds logic and good to me,  indeed index.html should be a skeleton (consider all was still a prototype)

**Comment by mudler** [comment]
@Ryuno-Ki  Ping me when it's ready to merge (please mention me so i don't miss your PR anymore). When you are on gitter i'll be glad to exchange few words with you :smiley:

**Comment by Ryuno-Ki** [comment]
http://cross-lfs.sabayonlinux.org/ is odd (c. f.    e577687)

I thought, sabayonlinux.org would belong to Sabayon staff - how is a subdomain a mirror than? O_o

@mudler Please provide feedback concerning the list bullets.

For now I opted to use [bullet](https://www.sabayon.org/sites/all/themes/sabayon/img/bullet.png) from `/sites/all/themes/sabayon/img/`, but I'd suggest moving that to `static.sabayon.org`. It's the image currently used on https://www.sabayon.org/mirrors

**Comment by Ryuno-Ki** [comment]
Ping @mudler.

I recommend to check out the branch locally and double-check the routes under /content. Today I could not see FontAwesome icons globally (read: on all pages), but saw a 200 in networks tab of my developer tools (Firefox).

**Comment by mudler** [comment]
i've been busy lately, but i can now work on it @Ryuno-Ki , what's the status? can i merge?

**Comment by Ryuno-Ki** [comment]
Currently moving houses, so I'm offline until Friday :-/

Looks like there are merge conflicts I'd need to investigate. But IIRC I walked through all files so far to clean up the Markdown in content directory. Next step would be to clean up the layout files (unifying)

**Comment by mudler** [comment]
I've added couple of articles to sync with what we have in the current website and i renamed "post" in "article" category, should be pretty straightforward

**Comment by Ryuno-Ki** [comment]
@mudler Found the time to resolve the merge conflicts (basically updating `16.04` to `16.07`).

Please check it out before merging.

**Comment by mudler** [comment]
cool! we can also test it live, we aren't still in production mode :) should i merge before the PR on -next?

**Comment by Ryuno-Ki** [comment]
Not sure, whether I understand you correctly, but you'd need to accept both, #14 and Sabayon/sabayon-website-next-theme#2.

**Pull request merged**
